// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0PFvyO4caNbFgGNEqsSYqh2-agGaxpg',
    appId: '1:1059905996481:web:f3cef7a5de1fe1c40df640',
    messagingSenderId: '1059905996481',
    projectId: 'flutter-final-project-a5a2c',
    authDomain: 'flutter-final-project-a5a2c.firebaseapp.com',
    storageBucket: 'flutter-final-project-a5a2c.appspot.com',
    measurementId: 'G-R36QSS9DT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABjEv1yK5yFKuxHplaZeuSfhjoKSKOLXo',
    appId: '1:1059905996481:android:2d780c7eb255f2ba0df640',
    messagingSenderId: '1059905996481',
    projectId: 'flutter-final-project-a5a2c',
    storageBucket: 'flutter-final-project-a5a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDov1ATMjpbv5poFzvDW3qt6GZGks6Qeb8',
    appId: '1:1059905996481:ios:d948e478fb14745f0df640',
    messagingSenderId: '1059905996481',
    projectId: 'flutter-final-project-a5a2c',
    storageBucket: 'flutter-final-project-a5a2c.appspot.com',
    iosBundleId: 'com.example.flutterFinalProject',
  );

}